In [2]:
import pandas as pd
import os

In [9]:
directory_path = 'data/twitter/'
files = os.listdir(directory_path)
data = []

In [10]:
for file in files:
    if file.endswith('.csv'):
        file_path = os.path.join(directory_path, file)
        df = pd.read_csv(file_path)
        data.append(df)

combined_data = pd.concat(data)

In [11]:
combined_data

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1806153949847900446,Thu Jun 27 02:33:53 +0000 2024,0,bahaya bgt ya jangan nempel CC di ecommerce,1806153949847900446,NaN,NaN,in,99!,0,0,0,https://x.com/gyuboology/status/18061539498479...,523205706,gyuboology
1,1806148630967177642,Thu Jun 27 02:12:44 +0000 2024,0,Bisanye nge tracking orang beli papir di e com...,1806148630967177642,NaN,NaN,in,Jakarta,0,0,0,https://x.com/Ezz404/status/1806148630967177642,240512616,Ezz404
2,1805437817901957201,Thu Jun 27 02:04:19 +0000 2024,0,@ibas404 Balik ke SMS Yg penting fizzo dan eco...,1806146510582866406,NaN,ibas404,in,"Kediri, Indonesia",0,0,0,https://x.com/itsna_nafiah/status/180614651058...,4363359373,itsna_nafiah
3,1805838532067606998,Thu Jun 27 00:50:48 +0000 2024,0,@geloraco Industri ecommerce otomotif Elektron...,1806128010963366307,NaN,geloraco,in,NaN,0,0,0,https://x.com/kangsander/status/18061280109633...,1584941053,kangsander
4,1806095814097600529,Wed Jun 26 22:42:52 +0000 2024,1,Pasar Fisik kok mulai sepi pada pindah kemana?...,1806095814097600529,https://pbs.twimg.com/ext_tw_video_thumb/18060...,NaN,in,Solo,0,0,0,https://x.com/masbambangnet/status/18060958140...,98997936,masbambangnet
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447,1799656581962908114,Sun Jun 09 04:15:39 +0000 2024,0,Riset menyatakan kecenderungan pengguna atau k...,1799656581962908114,NaN,NaN,in,"Jakarta, Indonesia",0,1,1,https://x.com/detikinet/status/179965658196290...,135815019,detikinet
448,1799654604764057808,Sun Jun 09 04:07:48 +0000 2024,0,E-Commerce Jadi Salah Satu Penopang Kinerja In...,1799654604764057808,https://pbs.twimg.com/media/GPmoJL4aIAAtvrS.png,NaN,in,NaN,0,0,0,https://x.com/arahkitamedia_/status/1799654604...,1741804247933665280,arahkitamedia_
449,1799554082312515969,Sat Jun 08 23:48:26 +0000 2024,0,@davidamzhustle PROFIT,1799589335383114011,NaN,davidamzhustle,in,Belfast,0,1,0,https://x.com/ChrisALavery/status/179958933538...,120499006,ChrisALavery
450,1799524862425260185,Sat Jun 08 19:34:10 +0000 2024,0,@LibertyCappy Pokemon?,1799525345302892593,NaN,LibertyCappy,in,NaN,0,0,0,https://x.com/ecomTrevor/status/17995253453028...,793644255130431488,ecomTrevor
451,1799507425797836927,Sat Jun 08 18:22:58 +0000 2024,0,Setahun yang lalu ecommerce kambuh lagi gue,1799507425797836927,NaN,NaN,in,"id +62 Jakarta, Indonesia",0,0,0,https://x.com/AlidarmansyahWp/status/179950742...,1322840737,AlidarmansyahWp

In [15]:
combined_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3853 entries, 0 to 451
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   conversation_id_str      3853 non-null   int64
 1   created_at               3853 non-null   object
 2   favorite_count           3853 non-null   int64
 3   full_text                3853 non-null   object
 4   id_str                   3853 non-null   int64
 5   image_url                533 non-null    object
 6   in_reply_to_screen_name  2024 non-null   object
 7   lang                     3853 non-null   object
 8   location                 2164 non-null   object
 9   quote_count              3853 non-null   int64
 10  reply_count              3853 non-null   int64
 11  retweet_count            3853 non-null   int64
 12  tweet_url                3853 non-null   object
 13  user_id_str              3853 non-null   int64
 14  username                 3853 non-null   object
dtypes: int64(7), object(8)
memory usage: 481.6+ KB

In [17]:
print(combined_data.isna().sum())

conversation_id_str           0
created_at                    0
favorite_count                0
full_text                     0
id_str                        0
image_url                  3320
in_reply_to_screen_name    1829
lang                          0
location                   1689
quote_count                   0
reply_count                   0
retweet_count                 0
tweet_url                     0
user_id_str                   0
username                      0
dtype: int64

In [18]:
print(combined_data.duplicated().sum())

3059

In [19]:
cleaned_data = combined_data.drop_duplicates()
cleaned_data

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1806153949847900446,Thu Jun 27 02:33:53 +0000 2024,0,bahaya bgt ya jangan nempel CC di ecommerce,1806153949847900446,NaN,NaN,in,99!,0,0,0,https://x.com/gyuboology/status/18061539498479...,523205706,gyuboology
1,1806148630967177642,Thu Jun 27 02:12:44 +0000 2024,0,Bisanye nge tracking orang beli papir di e com...,1806148630967177642,NaN,NaN,in,Jakarta,0,0,0,https://x.com/Ezz404/status/1806148630967177642,240512616,Ezz404
2,1805437817901957201,Thu Jun 27 02:04:19 +0000 2024,0,@ibas404 Balik ke SMS Yg penting fizzo dan eco...,1806146510582866406,NaN,ibas404,in,"Kediri, Indonesia",0,0,0,https://x.com/itsna_nafiah/status/180614651058...,4363359373,itsna_nafiah
3,1805838532067606998,Thu Jun 27 00:50:48 +0000 2024,0,@geloraco Industri ecommerce otomotif Elektron...,1806128010963366307,NaN,geloraco,in,NaN,0,0,0,https://x.com/kangsander/status/18061280109633...,1584941053,kangsander
4,1806095814097600529,Wed Jun 26 22:42:52 +0000 2024,1,Pasar Fisik kok mulai sepi pada pindah kemana?...,1806095814097600529,https://pbs.twimg.com/ext_tw_video_thumb/18060...,NaN,in,Solo,0,0,0,https://x.com/masbambangnet/status/18060958140...,98997936,masbambangnet
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
474,1799798402538156446,Sun Jun 09 13:39:12 +0000 2024,5,ini kenapa tiba-tiba banyak perintilan Sanrio ...,1799798402538156446,NaN,NaN,in,NaN,0,1,0,https://x.com/tartapplesauce/status/1799798402...,1060401853052084225,tartapplesauce
58,1805189118839931295,Mon Jun 24 10:39:59 +0000 2024,0,Bisa ga sih kl barangnya abis tuh ga dibikin a...,1805189118839931295,NaN,NaN,in,personal; kakna & niuâœ¨,0,1,0,https://x.com/ibabskuy/status/1805189118839931295,1265733578622595072,ibabskuy
126,1803784394009928146,Thu Jun 20 13:38:06 +0000 2024,421,Work! Butuh kerjaan please jadi admin ecommerc...,1803784394009928146,NaN,NaN,in,MENFESS SEMI-OTOMATIS,0,36,21,https://x.com/worksfess/status/180378439400992...,1244597361826885636,worksfess
128,1803763666200011011,Thu Jun 20 12:15:44 +0000 2024,4180,Atau beli aja di ecommerce buku sekolah terbit...,1803763666200011011,https://pbs.twimg.com/media/GQhBfXha0AAE5dF.jpg,NaN,in,Singapore,36,24,630,https://x.com/ainunnajib/status/18037636662000...,35167068,ainunnajib
278,1801501029042950312,Fri Jun 14 19:42:09 +0000 2024,0,@silverrmist_ Walau agak benci tapi ga bisa di...,1801701680779772196,NaN,silverrmist_,in,"East Java, Indonesia",0,1,0,https://x.com/xnyarisa/status/1801701680779772196,826155896,xnyarisa